spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/problemdb
    username: problem_user
    password: problem_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update  # You can change it to 'create' or 'validate' as per your requirements
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Spring Boot application settings
  application:
    name: problem-service

  # Eureka client configuration for service registration
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

  # Logging configuration
  logging:
    level:
      org.springframework: INFO
      com.codearena.problem_service: DEBUG
